# -*- coding: utf-8 -*-
"""Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ctf88IkZHaD4VWcN-U7nIssq93vdU4n9

# Task 6: Prediction Using Decision Tree Algorithm

# Importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# Importing dataset"""

dataset=pd.read_csv('Iris.csv')
dataset

dataset=dataset.drop(['Id'],axis=1)   # Dropping id column
dataset

dataset['Species'].unique()



dataset.info()

dataset.describe()

"""# Dealing with Categorical Variable"""

dataset['Species']=dataset['Species'].replace(to_replace='Iris-setosa',value=0)
dataset['Species']=dataset['Species'].replace(to_replace='Iris-versicolor',value=1)
dataset['Species']=dataset['Species'].replace(to_replace='Iris-virginica',value=2)

dataset

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

x

y

"""# Splitting the dataset"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

"""# Decision Tree Algorithm"""

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

pred=dtc.predict(x_test)
pred

"""# Tree Visualisation"""

from sklearn import tree

import graphviz

df=pd.read_csv('Iris.csv')

tree_vis=tree.export_graphviz(dtc,out_file=None,feature_names=df.drop(['Id','Species'],axis=1).keys(),
                     class_names=df['Species'].unique(),filled=True,rounded=True,
                    special_characters=True)

graphviz.Source(tree_vis)

"""# Prediction based on Custon Input"""

category=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

DT=np.array([[5.45 ,3.2, 5.6, 0.8]])
DT_pred=dtc.predict(DT)

DT_pred[0]

print(category[int(DT_pred[0])])

"""# Checking the Accuarcy"""

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,pred)
cm

acc=accuracy_score(y_test,pred)
acc

