# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8-1rsr0HqCFHjyR3q_r49sm4iF0kshJ

## **Siddhant Sehgal**

# **Task 3-Perform ‘Exploratory Data Analysis’ on dataset ‘SampleSuperstore'**

# Importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

"""# Importing Dataset"""

dataset=pd.read_csv('SampleSuperstore.csv')
dataset

"""# Expolatory Data Analysis"""

fig=px.bar(dataset,x="Ship Mode",title="Most Common Ship Mode")
fig.show()

"""As we can see from above graph that most prefered ship mode is Standard Class"""

seg=dataset['Segment'].value_counts()
seg

fig=px.pie(values=seg.values,names=seg.index)
fig.show()

"""Most Orders are Placed by Consumers"""



plt.figure(figsize=(16,8))
plt.bar('Sub-Category','Category', data=dataset)
plt.title('Category vs Sub Category')
plt.xlabel('Sub-Catgory')
plt.ylabel('Category')
plt.xticks(rotation=45)
plt.show()

"""Category Vs SubCategories"""



plt.figure(figsize=(12,10))
sns.heatmap(dataset.corr(),annot=True)

#!pip install plotly==4.5.2

px.sunburst(dataset,path=['Category','Sub-Category'],values='Sales')

"""Most of the sales is done in Technology Department

Graph Insights:-

1.   If u click on Technology on above graphs you can see that most of the sales in technology is of Mobile Phones
2.   If u click on Furniture on above graphs you can see that most of the sales in technology is of Tables and Chairs
3. If u click on Office Supplies on above graphs you can see that most of the sales in technology is of Storage and Binders


"""



px.sunburst(dataset,path=['Region'],values='Profit')

"""Most Profits are earned in West Region """



state_count=dataset['State'].value_counts()[:15]

px.bar(x=state_count.index,y=state_count.values,color=state_count.values)

"""Top 15 States occuring Frequently"""



sm=dataset['Ship Mode'].value_counts()
sm

fig=px.bar(dataset,x='Ship Mode',color='Category',hover_name='Region')
fig.show()



figsize=(15,10)
sns.pairplot(dataset,hue='Sub-Category')
plt.show



plt.figure(figsize=(10,4))
sns.lineplot('Discount','Profit', data=dataset , color='y',label='Discount')
plt.legend()
plt.show()



"""let us have a look at the total sales per state and the revenue generated."""

state_code = {'Alabama': 'AL','Alaska': 'AK','Arizona': 'AZ','Arkansas': 'AR','California': 'CA',
              'Colorado': 'CO','Connecticut': 'CT','Delaware': 'DE','Florida': 'FL','Georgia': 'GA',
              'Hawaii': 'HI','Idaho': 'ID','Illinois': 'IL','Indiana': 'IN','Iowa': 'IA','Kansas': 'KS',
              'Kentucky': 'KY','Louisiana': 'LA','Maine': 'ME','Maryland': 'MD','Massachusetts': 'MA',
              'Michigan': 'MI','Minnesota': 'MN','Mississippi': 'MS','Missouri': 'MO','Montana': 'MT',
              'Nebraska': 'NE','Nevada': 'NV','New Hampshire': 'NH','New Jersey': 'NJ','New Mexico': 'NM',
              'New York': 'NY','North Carolina': 'NC','North Dakota': 'ND','Ohio': 'OH','Oklahoma': 'OK',
              'Oregon': 'OR','Pennsylvania': 'PA','Rhode Island': 'RI','South Carolina': 'SC',
              'South Dakota': 'SD','Tennessee': 'TN','Texas': 'TX','Utah': 'UT','Vermont': 'VT',
              'Virginia': 'VA','District of Columbia': 'WA','Washington': 'WA','West Virginia': 'WV',
              'Wisconsin': 'WI','Wyoming': 'WY'}
dataset['state_code'] = dataset.State.apply(lambda x: state_code[x])

state_data = dataset[['Sales', 'Profit', 'state_code']].groupby(['state_code']).sum()


fig = go.Figure(data=go.Choropleth(
    locations=state_data.index, 
    z = state_data.Sales, 
    locationmode = 'USA-states', 
    colorscale = 'Reds',
    colorbar_title = 'Sales in USD',
))

fig.update_layout(
    title_text = 'Total State-Wise Sales',
    geo_scope='usa',
    height=800,
)

fig.show()



fig = go.Figure(data=go.Choropleth(
    locations=state_data.index, # Spatial coordinates
    z = state_data.Profit, # Data to be color-coded
    locationmode = 'USA-states', # set of locations match entries in `locations`
    colorscale = [[0, 'rgb(255,0,0)'], [0.25, 'rgb(255,255,255)'], [0.45, 'rgb(124,208,247)'], [0.6, 'rgb(97,255,140)'], [1, 'rgb(8,181,0)']],
#     reversescale = True,
    colorbar_title = 'Profits in USD',
))

fig.update_layout(
    title_text = 'Total State-Wise Profit/Loss',
    geo_scope='usa', # limite map scope to USA
    height=800,
)

fig.show()

"""From this we can understand:

In "Central" Region the profit and sales are less

Labels, Art, Paper, Fastners are sold less than the other products.

First class products are sold more than Second class, Standard class and Same day. So we should give discount more to other classes to increase the profit.

The Discount should not be more than 4% . When the Discount goes beyond 4 % the profit decreases . So we should try to keep the discount atmost 4 %.

Consumers gives less profit than other segment.
"""

